name: Update readme
 
on:
  schedule:
    # Se ejecuta cada hora de forma automática
    - cron: '0 * * * *'
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaña Actions
 
jobs:
  update-readme:
    name: Actualizar README con actividad de GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4.2.2
 
      - name: Insertar actividad reciente
        uses: jamesgeorge007/github-activity-readme@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Limita el número de acciones a mostrar (máximo 10)
          COMMIT_MSG: "Bot: Actividad reciente actualizada"
          MAX_LINES: 5 
